development:
  forest_env_secret: 448ec052cdfdf51babab23d2d9b73c3c81905c842bad5b4c559c449d8bfc958a
  forest_auth_secret: 3iUqBgvuN4I5Aimbb9rLlg
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
